### ISSUE TITLE
Fix warnings and test coverage reported with Cake build system

### ISSUE THREAD

**Issue by pleonex** [SceneGate/Yarhl#64]
After #60 some tools started to report new warnings. We need to take a look into them and them into the ignore rules or fix them. Also the test coverage seems to not be 100%, we may need to skip some test classes.

**Comment by priverop** [comment]
[This PR](https://github.com/SceneGate/Yarhl/pull/75) fixes every warning but: `File may only contain a single class` at _FileFormat/Converters.cs_, and _Text/Encodings/EscapeOutRangeEncoding.cs_.
