### ISSUE TITLE
Tutorials - How to use

### ISSUE THREAD

**Issue by priverop** [SceneGate/Yarhl#67]
The learning curve would be way better if we have some sort of tutorials with little examples:

1. Your first project: Reading and writing.
2. Binary2Po.
3. Custom Formats and Converting.

What it comes to my mind right now. Little examples to show what the library has to offer plus showing good practices.

**Comment by priverop** [comment]
So in which format this should be developped? As a folder with .cs? Just .md? Or maybe html and integrate it to https://scenegate.github.io?

**Comment by pleonex** [comment]
I have updated the DocFx configuration files to add 'articles'. We just need to create a MarkDown file per tutorial / article under `docs/articles` and add the title and link in `docs/articles/toc.yml`.

**Comment by priverop** [comment]
@pleonex this can be closed right? We can maybe create another issue for the Cookbook.

**Comment by pleonex** [comment]
Yes, that makes sense.
