### ISSUE TITLE
Add zlib deflate and inflate to Yarhl

### ISSUE THREAD

**Issue by Darkmet98** [SceneGate/Yarhl#88]
**Is your feature request related to a problem? Please describe.**
There's something zlib files that do not work with all c# libraries and with the C original library sample works.

**Describe the solution you'd like**
Add zlib's deflate and inflate to Yarhl in order to make programs that are easier to work with by zlib compressed files.

**Comment by pleonex** [comment]
We need to investigate first what's the problem with the files that other ZLIB libraries doesn't support.

**Comment by pleonex** [comment]
Closing as it was a problem with that specific format non-following the standard rather than with the implementation of zlib in standard libraries.
